# transfer detr weight name to mmdet weight name
# backbone:r50, neck:fpn

mmdet={}
for i in detr:
    temp=""
    # rpn transfer
    if i.split(".")[0]=="proposal_generator":
        temp+="rpn_head."
        if "conv" in i:
            temp+="rpn_conv."
            if "weight" in i:
                temp+="weight"
            else:
                temp+="bias"
        elif 'objectness_logits' in i:
            temp+="rpn_cls."
            if "weight" in i:
                temp+="weight"
            else:
                temp+="bias"
        elif "anchor_deltas" in i:
            temp+="rpn_reg."
            if "weight" in i:
                temp+="weight"
            else:
                temp+="bias"
        else:
            continue
    # fpn transfer
    elif "fpn" in i:
        temp+="neck."
        if "lateral" in i:
            temp+="lateral_convs."
            temp+=str(int(i.split(".")[1][-1])-2)
            temp+='.conv.'
            if "weight" in i:
                temp+="weight"
            else:
                temp+="bias"
        elif "output" in i:
            temp+="fpn_convs."
            temp+=str(int(i.split(".")[1][-1])-2)
            temp+='.conv.'
            if "weight" in i:
                temp+="weight"
            else:
                temp+="bias"
    # resnet transfer
    elif "bottom_up" in i:
        temp+="backbone."
        if "stem.conv1.weight" in i:
            temp+="conv1.weight"
        elif "stem.conv1.norm" in i:
            temp+="bn1."
            if "weight" in i:
                temp+="weight"
            elif "bias" in i:
                temp+="bias"
            elif "running_mean" in i:
                temp+="running_mean"
            elif "running_var" in i:
                temp+="running_var"
        elif "res" in i:
            temp+="layer"
            temp+=str(int(i.split(".")[2][-1])-1)
            temp+="."
            temp+=i.split(".")[3]
            temp+="."
            if "shortcut" in i:
                if "norm" not in i:
                    temp+="downsample.0.weight"
                else:
                    temp+="downsample.1."
                    if "weight" in i:
                        temp+="weight"
                    elif "bias" in i:
                        temp+="bias"
                    elif "running_mean" in i:
                        temp+="running_mean"
                    elif "running_var" in i:
                        temp+="running_var"
            else:
                if "norm" not in i:
                    temp+=i.split(".")[4]
                    temp+=".weight"
                else:
                    temp=temp+"bn"+str(int(i.split(".")[4][-1]))+"."
                    if "weight" in i:
                        temp+="weight"
                    elif "bias" in i:
                        temp+="bias"
                    elif "running_mean" in i:
                        temp+="running_mean"
                    elif "running_var" in i:
                        temp+="running_var"
    # roi transform
    elif "roi_heads" in i:
        temp+="roi_head.bbox_head."
        if "box_head" in i:
            temp+="shared_fcs."
            temp+=str(int(i.split(".")[2][-1])-1)
            temp+='.'
            if "weight" in i:
                temp+="weight"
            elif "bias" in i:
                temp+="bias"
        else:
            if "cls_score" in i:
                temp+="fc_cls."
                if "weight" in i:
                    temp+="weight"
                elif "bias" in i:
                    temp+="bias"
            else:
                temp+="fc_reg."
                if "weight" in i:
                    temp+="weight"
                elif "bias" in i:
                    temp+="bias"
    mmdet[temp]=detr[i]
                    
            




'''mmdet form
backbone.conv1.weight
backbone.bn1.weight
backbone.bn1.bias
backbone.bn1.running_mean
backbone.bn1.running_var
backbone.bn1.num_batches_tracked
backbone.layer1.0.conv1.weight
backbone.layer1.0.bn1.weight
backbone.layer1.0.bn1.bias
backbone.layer1.0.bn1.running_mean
backbone.layer1.0.bn1.running_var
backbone.layer1.0.bn1.num_batches_tracked
backbone.layer1.0.conv2.weight
backbone.layer1.0.bn2.weight
backbone.layer1.0.bn2.bias
backbone.layer1.0.bn2.running_mean
backbone.layer1.0.bn2.running_var
backbone.layer1.0.bn2.num_batches_tracked
backbone.layer1.0.conv3.weight
backbone.layer1.0.bn3.weight
backbone.layer1.0.bn3.bias
backbone.layer1.0.bn3.running_mean
backbone.layer1.0.bn3.running_var
backbone.layer1.0.bn3.num_batches_tracked
backbone.layer1.0.downsample.0.weight
backbone.layer1.0.downsample.1.weight
backbone.layer1.0.downsample.1.bias
backbone.layer1.0.downsample.1.running_mean
backbone.layer1.0.downsample.1.running_var
backbone.layer1.0.downsample.1.num_batches_tracked
backbone.layer1.1.conv1.weight
backbone.layer1.1.bn1.weight
backbone.layer1.1.bn1.bias
backbone.layer1.1.bn1.running_mean
backbone.layer1.1.bn1.running_var
backbone.layer1.1.bn1.num_batches_tracked
backbone.layer1.1.conv2.weight
backbone.layer1.1.bn2.weight
backbone.layer1.1.bn2.bias
backbone.layer1.1.bn2.running_mean
backbone.layer1.1.bn2.running_var
backbone.layer1.1.bn2.num_batches_tracked
backbone.layer1.1.conv3.weight
backbone.layer1.1.bn3.weight
backbone.layer1.1.bn3.bias
backbone.layer1.1.bn3.running_mean
backbone.layer1.1.bn3.running_var
backbone.layer1.1.bn3.num_batches_tracked
backbone.layer1.2.conv1.weight
backbone.layer1.2.bn1.weight
backbone.layer1.2.bn1.bias
backbone.layer1.2.bn1.running_mean
backbone.layer1.2.bn1.running_var
backbone.layer1.2.bn1.num_batches_tracked
backbone.layer1.2.conv2.weight
backbone.layer1.2.bn2.weight
backbone.layer1.2.bn2.bias
backbone.layer1.2.bn2.running_mean
backbone.layer1.2.bn2.running_var
backbone.layer1.2.bn2.num_batches_tracked
backbone.layer1.2.conv3.weight
backbone.layer1.2.bn3.weight
backbone.layer1.2.bn3.bias
backbone.layer1.2.bn3.running_mean
backbone.layer1.2.bn3.running_var
backbone.layer1.2.bn3.num_batches_tracked
backbone.layer2.0.conv1.weight
backbone.layer2.0.bn1.weight
backbone.layer2.0.bn1.bias
backbone.layer2.0.bn1.running_mean
backbone.layer2.0.bn1.running_var
backbone.layer2.0.bn1.num_batches_tracked
backbone.layer2.0.conv2.weight
backbone.layer2.0.bn2.weight
backbone.layer2.0.bn2.bias
backbone.layer2.0.bn2.running_mean
backbone.layer2.0.bn2.running_var
backbone.layer2.0.bn2.num_batches_tracked
backbone.layer2.0.conv3.weight
backbone.layer2.0.bn3.weight
backbone.layer2.0.bn3.bias
backbone.layer2.0.bn3.running_mean
backbone.layer2.0.bn3.running_var
backbone.layer2.0.bn3.num_batches_tracked
backbone.layer2.0.downsample.0.weight
backbone.layer2.0.downsample.1.weight
backbone.layer2.0.downsample.1.bias
backbone.layer2.0.downsample.1.running_mean
backbone.layer2.0.downsample.1.running_var
backbone.layer2.0.downsample.1.num_batches_tracked
backbone.layer2.1.conv1.weight
backbone.layer2.1.bn1.weight
backbone.layer2.1.bn1.bias
backbone.layer2.1.bn1.running_mean
backbone.layer2.1.bn1.running_var
backbone.layer2.1.bn1.num_batches_tracked
backbone.layer2.1.conv2.weight
backbone.layer2.1.bn2.weight
backbone.layer2.1.bn2.bias
backbone.layer2.1.bn2.running_mean
backbone.layer2.1.bn2.running_var
backbone.layer2.1.bn2.num_batches_tracked
backbone.layer2.1.conv3.weight
backbone.layer2.1.bn3.weight
backbone.layer2.1.bn3.bias
backbone.layer2.1.bn3.running_mean
backbone.layer2.1.bn3.running_var
backbone.layer2.1.bn3.num_batches_tracked
backbone.layer2.2.conv1.weight
backbone.layer2.2.bn1.weight
backbone.layer2.2.bn1.bias
backbone.layer2.2.bn1.running_mean
backbone.layer2.2.bn1.running_var
backbone.layer2.2.bn1.num_batches_tracked
backbone.layer2.2.conv2.weight
backbone.layer2.2.bn2.weight
backbone.layer2.2.bn2.bias
backbone.layer2.2.bn2.running_mean
backbone.layer2.2.bn2.running_var
backbone.layer2.2.bn2.num_batches_tracked
backbone.layer2.2.conv3.weight
backbone.layer2.2.bn3.weight
backbone.layer2.2.bn3.bias
backbone.layer2.2.bn3.running_mean
backbone.layer2.2.bn3.running_var
backbone.layer2.2.bn3.num_batches_tracked
backbone.layer2.3.conv1.weight
backbone.layer2.3.bn1.weight
backbone.layer2.3.bn1.bias
backbone.layer2.3.bn1.running_mean
backbone.layer2.3.bn1.running_var
backbone.layer2.3.bn1.num_batches_tracked
backbone.layer2.3.conv2.weight
backbone.layer2.3.bn2.weight
backbone.layer2.3.bn2.bias
backbone.layer2.3.bn2.running_mean
backbone.layer2.3.bn2.running_var
backbone.layer2.3.bn2.num_batches_tracked
backbone.layer2.3.conv3.weight
backbone.layer2.3.bn3.weight
backbone.layer2.3.bn3.bias
backbone.layer2.3.bn3.running_mean
backbone.layer2.3.bn3.running_var
backbone.layer2.3.bn3.num_batches_tracked
backbone.layer3.0.conv1.weight
backbone.layer3.0.bn1.weight
backbone.layer3.0.bn1.bias
backbone.layer3.0.bn1.running_mean
backbone.layer3.0.bn1.running_var
backbone.layer3.0.bn1.num_batches_tracked
backbone.layer3.0.conv2.weight
backbone.layer3.0.bn2.weight
backbone.layer3.0.bn2.bias
backbone.layer3.0.bn2.running_mean
backbone.layer3.0.bn2.running_var
backbone.layer3.0.bn2.num_batches_tracked
backbone.layer3.0.conv3.weight
backbone.layer3.0.bn3.weight
backbone.layer3.0.bn3.bias
backbone.layer3.0.bn3.running_mean
backbone.layer3.0.bn3.running_var
backbone.layer3.0.bn3.num_batches_tracked
backbone.layer3.0.downsample.0.weight
backbone.layer3.0.downsample.1.weight
backbone.layer3.0.downsample.1.bias
backbone.layer3.0.downsample.1.running_mean
backbone.layer3.0.downsample.1.running_var
backbone.layer3.0.downsample.1.num_batches_tracked
backbone.layer3.1.conv1.weight
backbone.layer3.1.bn1.weight
backbone.layer3.1.bn1.bias
backbone.layer3.1.bn1.running_mean
backbone.layer3.1.bn1.running_var
backbone.layer3.1.bn1.num_batches_tracked
backbone.layer3.1.conv2.weight
backbone.layer3.1.bn2.weight
backbone.layer3.1.bn2.bias
backbone.layer3.1.bn2.running_mean
backbone.layer3.1.bn2.running_var
backbone.layer3.1.bn2.num_batches_tracked
backbone.layer3.1.conv3.weight
backbone.layer3.1.bn3.weight
backbone.layer3.1.bn3.bias
backbone.layer3.1.bn3.running_mean
backbone.layer3.1.bn3.running_var
backbone.layer3.1.bn3.num_batches_tracked
backbone.layer3.2.conv1.weight
backbone.layer3.2.bn1.weight
backbone.layer3.2.bn1.bias
backbone.layer3.2.bn1.running_mean
backbone.layer3.2.bn1.running_var
backbone.layer3.2.bn1.num_batches_tracked
backbone.layer3.2.conv2.weight
backbone.layer3.2.bn2.weight
backbone.layer3.2.bn2.bias
backbone.layer3.2.bn2.running_mean
backbone.layer3.2.bn2.running_var
backbone.layer3.2.bn2.num_batches_tracked
backbone.layer3.2.conv3.weight
backbone.layer3.2.bn3.weight
backbone.layer3.2.bn3.bias
backbone.layer3.2.bn3.running_mean
backbone.layer3.2.bn3.running_var
backbone.layer3.2.bn3.num_batches_tracked
backbone.layer3.3.conv1.weight
backbone.layer3.3.bn1.weight
backbone.layer3.3.bn1.bias
backbone.layer3.3.bn1.running_mean
backbone.layer3.3.bn1.running_var
backbone.layer3.3.bn1.num_batches_tracked
backbone.layer3.3.conv2.weight
backbone.layer3.3.bn2.weight
backbone.layer3.3.bn2.bias
backbone.layer3.3.bn2.running_mean
backbone.layer3.3.bn2.running_var
backbone.layer3.3.bn2.num_batches_tracked
backbone.layer3.3.conv3.weight
backbone.layer3.3.bn3.weight
backbone.layer3.3.bn3.bias
backbone.layer3.3.bn3.running_mean
backbone.layer3.3.bn3.running_var
backbone.layer3.3.bn3.num_batches_tracked
backbone.layer3.4.conv1.weight
backbone.layer3.4.bn1.weight
backbone.layer3.4.bn1.bias
backbone.layer3.4.bn1.running_mean
backbone.layer3.4.bn1.running_var
backbone.layer3.4.bn1.num_batches_tracked
backbone.layer3.4.conv2.weight
backbone.layer3.4.bn2.weight
backbone.layer3.4.bn2.bias
backbone.layer3.4.bn2.running_mean
backbone.layer3.4.bn2.running_var
backbone.layer3.4.bn2.num_batches_tracked
backbone.layer3.4.conv3.weight
backbone.layer3.4.bn3.weight
backbone.layer3.4.bn3.bias
backbone.layer3.4.bn3.running_mean
backbone.layer3.4.bn3.running_var
backbone.layer3.4.bn3.num_batches_tracked
backbone.layer3.5.conv1.weight
backbone.layer3.5.bn1.weight
backbone.layer3.5.bn1.bias
backbone.layer3.5.bn1.running_mean
backbone.layer3.5.bn1.running_var
backbone.layer3.5.bn1.num_batches_tracked
backbone.layer3.5.conv2.weight
backbone.layer3.5.bn2.weight
backbone.layer3.5.bn2.bias
backbone.layer3.5.bn2.running_mean
backbone.layer3.5.bn2.running_var
backbone.layer3.5.bn2.num_batches_tracked
backbone.layer3.5.conv3.weight
backbone.layer3.5.bn3.weight
backbone.layer3.5.bn3.bias
backbone.layer3.5.bn3.running_mean
backbone.layer3.5.bn3.running_var
backbone.layer3.5.bn3.num_batches_tracked
backbone.layer4.0.conv1.weight
backbone.layer4.0.bn1.weight
backbone.layer4.0.bn1.bias
backbone.layer4.0.bn1.running_mean
backbone.layer4.0.bn1.running_var
backbone.layer4.0.bn1.num_batches_tracked
backbone.layer4.0.conv2.weight
backbone.layer4.0.bn2.weight
backbone.layer4.0.bn2.bias
backbone.layer4.0.bn2.running_mean
backbone.layer4.0.bn2.running_var
backbone.layer4.0.bn2.num_batches_tracked
backbone.layer4.0.conv3.weight
backbone.layer4.0.bn3.weight
backbone.layer4.0.bn3.bias
backbone.layer4.0.bn3.running_mean
backbone.layer4.0.bn3.running_var
backbone.layer4.0.bn3.num_batches_tracked
backbone.layer4.0.downsample.0.weight
backbone.layer4.0.downsample.1.weight
backbone.layer4.0.downsample.1.bias
backbone.layer4.0.downsample.1.running_mean
backbone.layer4.0.downsample.1.running_var
backbone.layer4.0.downsample.1.num_batches_tracked
backbone.layer4.1.conv1.weight
backbone.layer4.1.bn1.weight
backbone.layer4.1.bn1.bias
backbone.layer4.1.bn1.running_mean
backbone.layer4.1.bn1.running_var
backbone.layer4.1.bn1.num_batches_tracked
backbone.layer4.1.conv2.weight
backbone.layer4.1.bn2.weight
backbone.layer4.1.bn2.bias
backbone.layer4.1.bn2.running_mean
backbone.layer4.1.bn2.running_var
backbone.layer4.1.bn2.num_batches_tracked
backbone.layer4.1.conv3.weight
backbone.layer4.1.bn3.weight
backbone.layer4.1.bn3.bias
backbone.layer4.1.bn3.running_mean
backbone.layer4.1.bn3.running_var
backbone.layer4.1.bn3.num_batches_tracked
backbone.layer4.2.conv1.weight
backbone.layer4.2.bn1.weight
backbone.layer4.2.bn1.bias
backbone.layer4.2.bn1.running_mean
backbone.layer4.2.bn1.running_var
backbone.layer4.2.bn1.num_batches_tracked
backbone.layer4.2.conv2.weight
backbone.layer4.2.bn2.weight
backbone.layer4.2.bn2.bias
backbone.layer4.2.bn2.running_mean
backbone.layer4.2.bn2.running_var
backbone.layer4.2.bn2.num_batches_tracked
backbone.layer4.2.conv3.weight
backbone.layer4.2.bn3.weight
backbone.layer4.2.bn3.bias
backbone.layer4.2.bn3.running_mean
backbone.layer4.2.bn3.running_var
backbone.layer4.2.bn3.num_batches_tracked
neck.lateral_convs.0.conv.weight
neck.lateral_convs.0.conv.bias
neck.lateral_convs.1.conv.weight
neck.lateral_convs.1.conv.bias
neck.lateral_convs.2.conv.weight
neck.lateral_convs.2.conv.bias
neck.lateral_convs.3.conv.weight
neck.lateral_convs.3.conv.bias
neck.fpn_convs.0.conv.weight
neck.fpn_convs.0.conv.bias
neck.fpn_convs.1.conv.weight
neck.fpn_convs.1.conv.bias
neck.fpn_convs.2.conv.weight
neck.fpn_convs.2.conv.bias
neck.fpn_convs.3.conv.weight
neck.fpn_convs.3.conv.bias
rpn_head.rpn_conv.weight
rpn_head.rpn_conv.bias
rpn_head.rpn_cls.weight
rpn_head.rpn_cls.bias
rpn_head.rpn_reg.weight
rpn_head.rpn_reg.bias
roi_head.bbox_head.fc_cls.weight
roi_head.bbox_head.fc_cls.bias
roi_head.bbox_head.fc_reg.weight
roi_head.bbox_head.fc_reg.bias
roi_head.bbox_head.shared_fcs.0.weight
roi_head.bbox_head.shared_fcs.0.bias
roi_head.bbox_head.shared_fcs.1.weight
roi_head.bbox_head.shared_fcs.1.bias
'''

'''detr form
backbone.fpn_lateral2.weight
backbone.fpn_lateral2.bias
backbone.fpn_output2.weight
backbone.fpn_output2.bias
backbone.fpn_lateral3.weight
backbone.fpn_lateral3.bias
backbone.fpn_output3.weight
backbone.fpn_output3.bias
backbone.fpn_lateral4.weight
backbone.fpn_lateral4.bias
backbone.fpn_output4.weight
backbone.fpn_output4.bias
backbone.fpn_lateral5.weight
backbone.fpn_lateral5.bias
backbone.fpn_output5.weight
backbone.fpn_output5.bias
backbone.bottom_up.stem.conv1.weight
backbone.bottom_up.stem.conv1.norm.weight
backbone.bottom_up.stem.conv1.norm.bias
backbone.bottom_up.stem.conv1.norm.running_mean
backbone.bottom_up.stem.conv1.norm.running_var
backbone.bottom_up.res2.0.shortcut.weight
backbone.bottom_up.res2.0.shortcut.norm.weight
backbone.bottom_up.res2.0.shortcut.norm.bias
backbone.bottom_up.res2.0.shortcut.norm.running_mean
backbone.bottom_up.res2.0.shortcut.norm.running_var
backbone.bottom_up.res2.0.conv1.weight
backbone.bottom_up.res2.0.conv1.norm.weight
backbone.bottom_up.res2.0.conv1.norm.bias
backbone.bottom_up.res2.0.conv1.norm.running_mean
backbone.bottom_up.res2.0.conv1.norm.running_var
backbone.bottom_up.res2.0.conv2.weight
backbone.bottom_up.res2.0.conv2.norm.weight
backbone.bottom_up.res2.0.conv2.norm.bias
backbone.bottom_up.res2.0.conv2.norm.running_mean
backbone.bottom_up.res2.0.conv2.norm.running_var
backbone.bottom_up.res2.0.conv3.weight
backbone.bottom_up.res2.0.conv3.norm.weight
backbone.bottom_up.res2.0.conv3.norm.bias
backbone.bottom_up.res2.0.conv3.norm.running_mean
backbone.bottom_up.res2.0.conv3.norm.running_var
backbone.bottom_up.res2.1.conv1.weight
backbone.bottom_up.res2.1.conv1.norm.weight
backbone.bottom_up.res2.1.conv1.norm.bias
backbone.bottom_up.res2.1.conv1.norm.running_mean
backbone.bottom_up.res2.1.conv1.norm.running_var
backbone.bottom_up.res2.1.conv2.weight
backbone.bottom_up.res2.1.conv2.norm.weight
backbone.bottom_up.res2.1.conv2.norm.bias
backbone.bottom_up.res2.1.conv2.norm.running_mean
backbone.bottom_up.res2.1.conv2.norm.running_var
backbone.bottom_up.res2.1.conv3.weight
backbone.bottom_up.res2.1.conv3.norm.weight
backbone.bottom_up.res2.1.conv3.norm.bias
backbone.bottom_up.res2.1.conv3.norm.running_mean
backbone.bottom_up.res2.1.conv3.norm.running_var
backbone.bottom_up.res2.2.conv1.weight
backbone.bottom_up.res2.2.conv1.norm.weight
backbone.bottom_up.res2.2.conv1.norm.bias
backbone.bottom_up.res2.2.conv1.norm.running_mean
backbone.bottom_up.res2.2.conv1.norm.running_var
backbone.bottom_up.res2.2.conv2.weight
backbone.bottom_up.res2.2.conv2.norm.weight
backbone.bottom_up.res2.2.conv2.norm.bias
backbone.bottom_up.res2.2.conv2.norm.running_mean
backbone.bottom_up.res2.2.conv2.norm.running_var
backbone.bottom_up.res2.2.conv3.weight
backbone.bottom_up.res2.2.conv3.norm.weight
backbone.bottom_up.res2.2.conv3.norm.bias
backbone.bottom_up.res2.2.conv3.norm.running_mean
backbone.bottom_up.res2.2.conv3.norm.running_var
backbone.bottom_up.res3.0.shortcut.weight
backbone.bottom_up.res3.0.shortcut.norm.weight
backbone.bottom_up.res3.0.shortcut.norm.bias
backbone.bottom_up.res3.0.shortcut.norm.running_mean
backbone.bottom_up.res3.0.shortcut.norm.running_var
backbone.bottom_up.res3.0.conv1.weight
backbone.bottom_up.res3.0.conv1.norm.weight
backbone.bottom_up.res3.0.conv1.norm.bias
backbone.bottom_up.res3.0.conv1.norm.running_mean
backbone.bottom_up.res3.0.conv1.norm.running_var
backbone.bottom_up.res3.0.conv2.weight
backbone.bottom_up.res3.0.conv2.norm.weight
backbone.bottom_up.res3.0.conv2.norm.bias
backbone.bottom_up.res3.0.conv2.norm.running_mean
backbone.bottom_up.res3.0.conv2.norm.running_var
backbone.bottom_up.res3.0.conv3.weight
backbone.bottom_up.res3.0.conv3.norm.weight
backbone.bottom_up.res3.0.conv3.norm.bias
backbone.bottom_up.res3.0.conv3.norm.running_mean
backbone.bottom_up.res3.0.conv3.norm.running_var
backbone.bottom_up.res3.1.conv1.weight
backbone.bottom_up.res3.1.conv1.norm.weight
backbone.bottom_up.res3.1.conv1.norm.bias
backbone.bottom_up.res3.1.conv1.norm.running_mean
backbone.bottom_up.res3.1.conv1.norm.running_var
backbone.bottom_up.res3.1.conv2.weight
backbone.bottom_up.res3.1.conv2.norm.weight
backbone.bottom_up.res3.1.conv2.norm.bias
backbone.bottom_up.res3.1.conv2.norm.running_mean
backbone.bottom_up.res3.1.conv2.norm.running_var
backbone.bottom_up.res3.1.conv3.weight
backbone.bottom_up.res3.1.conv3.norm.weight
backbone.bottom_up.res3.1.conv3.norm.bias
backbone.bottom_up.res3.1.conv3.norm.running_mean
backbone.bottom_up.res3.1.conv3.norm.running_var
backbone.bottom_up.res3.2.conv1.weight
backbone.bottom_up.res3.2.conv1.norm.weight
backbone.bottom_up.res3.2.conv1.norm.bias
backbone.bottom_up.res3.2.conv1.norm.running_mean
backbone.bottom_up.res3.2.conv1.norm.running_var
backbone.bottom_up.res3.2.conv2.weight
backbone.bottom_up.res3.2.conv2.norm.weight
backbone.bottom_up.res3.2.conv2.norm.bias
backbone.bottom_up.res3.2.conv2.norm.running_mean
backbone.bottom_up.res3.2.conv2.norm.running_var
backbone.bottom_up.res3.2.conv3.weight
backbone.bottom_up.res3.2.conv3.norm.weight
backbone.bottom_up.res3.2.conv3.norm.bias
backbone.bottom_up.res3.2.conv3.norm.running_mean
backbone.bottom_up.res3.2.conv3.norm.running_var
backbone.bottom_up.res3.3.conv1.weight
backbone.bottom_up.res3.3.conv1.norm.weight
backbone.bottom_up.res3.3.conv1.norm.bias
backbone.bottom_up.res3.3.conv1.norm.running_mean
backbone.bottom_up.res3.3.conv1.norm.running_var
backbone.bottom_up.res3.3.conv2.weight
backbone.bottom_up.res3.3.conv2.norm.weight
backbone.bottom_up.res3.3.conv2.norm.bias
backbone.bottom_up.res3.3.conv2.norm.running_mean
backbone.bottom_up.res3.3.conv2.norm.running_var
backbone.bottom_up.res3.3.conv3.weight
backbone.bottom_up.res3.3.conv3.norm.weight
backbone.bottom_up.res3.3.conv3.norm.bias
backbone.bottom_up.res3.3.conv3.norm.running_mean
backbone.bottom_up.res3.3.conv3.norm.running_var
backbone.bottom_up.res4.0.shortcut.weight
backbone.bottom_up.res4.0.shortcut.norm.weight
backbone.bottom_up.res4.0.shortcut.norm.bias
backbone.bottom_up.res4.0.shortcut.norm.running_mean
backbone.bottom_up.res4.0.shortcut.norm.running_var
backbone.bottom_up.res4.0.conv1.weight
backbone.bottom_up.res4.0.conv1.norm.weight
backbone.bottom_up.res4.0.conv1.norm.bias
backbone.bottom_up.res4.0.conv1.norm.running_mean
backbone.bottom_up.res4.0.conv1.norm.running_var
backbone.bottom_up.res4.0.conv2.weight
backbone.bottom_up.res4.0.conv2.norm.weight
backbone.bottom_up.res4.0.conv2.norm.bias
backbone.bottom_up.res4.0.conv2.norm.running_mean
backbone.bottom_up.res4.0.conv2.norm.running_var
backbone.bottom_up.res4.0.conv3.weight
backbone.bottom_up.res4.0.conv3.norm.weight
backbone.bottom_up.res4.0.conv3.norm.bias
backbone.bottom_up.res4.0.conv3.norm.running_mean
backbone.bottom_up.res4.0.conv3.norm.running_var
backbone.bottom_up.res4.1.conv1.weight
backbone.bottom_up.res4.1.conv1.norm.weight
backbone.bottom_up.res4.1.conv1.norm.bias
backbone.bottom_up.res4.1.conv1.norm.running_mean
backbone.bottom_up.res4.1.conv1.norm.running_var
backbone.bottom_up.res4.1.conv2.weight
backbone.bottom_up.res4.1.conv2.norm.weight
backbone.bottom_up.res4.1.conv2.norm.bias
backbone.bottom_up.res4.1.conv2.norm.running_mean
backbone.bottom_up.res4.1.conv2.norm.running_var
backbone.bottom_up.res4.1.conv3.weight
backbone.bottom_up.res4.1.conv3.norm.weight
backbone.bottom_up.res4.1.conv3.norm.bias
backbone.bottom_up.res4.1.conv3.norm.running_mean
backbone.bottom_up.res4.1.conv3.norm.running_var
backbone.bottom_up.res4.2.conv1.weight
backbone.bottom_up.res4.2.conv1.norm.weight
backbone.bottom_up.res4.2.conv1.norm.bias
backbone.bottom_up.res4.2.conv1.norm.running_mean
backbone.bottom_up.res4.2.conv1.norm.running_var
backbone.bottom_up.res4.2.conv2.weight
backbone.bottom_up.res4.2.conv2.norm.weight
backbone.bottom_up.res4.2.conv2.norm.bias
backbone.bottom_up.res4.2.conv2.norm.running_mean
backbone.bottom_up.res4.2.conv2.norm.running_var
backbone.bottom_up.res4.2.conv3.weight
backbone.bottom_up.res4.2.conv3.norm.weight
backbone.bottom_up.res4.2.conv3.norm.bias
backbone.bottom_up.res4.2.conv3.norm.running_mean
backbone.bottom_up.res4.2.conv3.norm.running_var
backbone.bottom_up.res4.3.conv1.weight
backbone.bottom_up.res4.3.conv1.norm.weight
backbone.bottom_up.res4.3.conv1.norm.bias
backbone.bottom_up.res4.3.conv1.norm.running_mean
backbone.bottom_up.res4.3.conv1.norm.running_var
backbone.bottom_up.res4.3.conv2.weight
backbone.bottom_up.res4.3.conv2.norm.weight
backbone.bottom_up.res4.3.conv2.norm.bias
backbone.bottom_up.res4.3.conv2.norm.running_mean
backbone.bottom_up.res4.3.conv2.norm.running_var
backbone.bottom_up.res4.3.conv3.weight
backbone.bottom_up.res4.3.conv3.norm.weight
backbone.bottom_up.res4.3.conv3.norm.bias
backbone.bottom_up.res4.3.conv3.norm.running_mean
backbone.bottom_up.res4.3.conv3.norm.running_var
backbone.bottom_up.res4.4.conv1.weight
backbone.bottom_up.res4.4.conv1.norm.weight
backbone.bottom_up.res4.4.conv1.norm.bias
backbone.bottom_up.res4.4.conv1.norm.running_mean
backbone.bottom_up.res4.4.conv1.norm.running_var
backbone.bottom_up.res4.4.conv2.weight
backbone.bottom_up.res4.4.conv2.norm.weight
backbone.bottom_up.res4.4.conv2.norm.bias
backbone.bottom_up.res4.4.conv2.norm.running_mean
backbone.bottom_up.res4.4.conv2.norm.running_var
backbone.bottom_up.res4.4.conv3.weight
backbone.bottom_up.res4.4.conv3.norm.weight
backbone.bottom_up.res4.4.conv3.norm.bias
backbone.bottom_up.res4.4.conv3.norm.running_mean
backbone.bottom_up.res4.4.conv3.norm.running_var
backbone.bottom_up.res4.5.conv1.weight
backbone.bottom_up.res4.5.conv1.norm.weight
backbone.bottom_up.res4.5.conv1.norm.bias
backbone.bottom_up.res4.5.conv1.norm.running_mean
backbone.bottom_up.res4.5.conv1.norm.running_var
backbone.bottom_up.res4.5.conv2.weight
backbone.bottom_up.res4.5.conv2.norm.weight
backbone.bottom_up.res4.5.conv2.norm.bias
backbone.bottom_up.res4.5.conv2.norm.running_mean
backbone.bottom_up.res4.5.conv2.norm.running_var
backbone.bottom_up.res4.5.conv3.weight
backbone.bottom_up.res4.5.conv3.norm.weight
backbone.bottom_up.res4.5.conv3.norm.bias
backbone.bottom_up.res4.5.conv3.norm.running_mean
backbone.bottom_up.res4.5.conv3.norm.running_var
backbone.bottom_up.res5.0.shortcut.weight
backbone.bottom_up.res5.0.shortcut.norm.weight
backbone.bottom_up.res5.0.shortcut.norm.bias
backbone.bottom_up.res5.0.shortcut.norm.running_mean
backbone.bottom_up.res5.0.shortcut.norm.running_var
backbone.bottom_up.res5.0.conv1.weight
backbone.bottom_up.res5.0.conv1.norm.weight
backbone.bottom_up.res5.0.conv1.norm.bias
backbone.bottom_up.res5.0.conv1.norm.running_mean
backbone.bottom_up.res5.0.conv1.norm.running_var
backbone.bottom_up.res5.0.conv2.weight
backbone.bottom_up.res5.0.conv2.norm.weight
backbone.bottom_up.res5.0.conv2.norm.bias
backbone.bottom_up.res5.0.conv2.norm.running_mean
backbone.bottom_up.res5.0.conv2.norm.running_var
backbone.bottom_up.res5.0.conv3.weight
backbone.bottom_up.res5.0.conv3.norm.weight
backbone.bottom_up.res5.0.conv3.norm.bias
backbone.bottom_up.res5.0.conv3.norm.running_mean
backbone.bottom_up.res5.0.conv3.norm.running_var
backbone.bottom_up.res5.1.conv1.weight
backbone.bottom_up.res5.1.conv1.norm.weight
backbone.bottom_up.res5.1.conv1.norm.bias
backbone.bottom_up.res5.1.conv1.norm.running_mean
backbone.bottom_up.res5.1.conv1.norm.running_var
backbone.bottom_up.res5.1.conv2.weight
backbone.bottom_up.res5.1.conv2.norm.weight
backbone.bottom_up.res5.1.conv2.norm.bias
backbone.bottom_up.res5.1.conv2.norm.running_mean
backbone.bottom_up.res5.1.conv2.norm.running_var
backbone.bottom_up.res5.1.conv3.weight
backbone.bottom_up.res5.1.conv3.norm.weight
backbone.bottom_up.res5.1.conv3.norm.bias
backbone.bottom_up.res5.1.conv3.norm.running_mean
backbone.bottom_up.res5.1.conv3.norm.running_var
backbone.bottom_up.res5.2.conv1.weight
backbone.bottom_up.res5.2.conv1.norm.weight
backbone.bottom_up.res5.2.conv1.norm.bias
backbone.bottom_up.res5.2.conv1.norm.running_mean
backbone.bottom_up.res5.2.conv1.norm.running_var
backbone.bottom_up.res5.2.conv2.weight
backbone.bottom_up.res5.2.conv2.norm.weight
backbone.bottom_up.res5.2.conv2.norm.bias
backbone.bottom_up.res5.2.conv2.norm.running_mean
backbone.bottom_up.res5.2.conv2.norm.running_var
backbone.bottom_up.res5.2.conv3.weight
backbone.bottom_up.res5.2.conv3.norm.weight
backbone.bottom_up.res5.2.conv3.norm.bias
backbone.bottom_up.res5.2.conv3.norm.running_mean
backbone.bottom_up.res5.2.conv3.norm.running_var
proposal_generator.rpn_head.conv.weight
proposal_generator.rpn_head.conv.bias
proposal_generator.rpn_head.objectness_logits.weight
proposal_generator.rpn_head.objectness_logits.bias
proposal_generator.rpn_head.anchor_deltas.weight
proposal_generator.rpn_head.anchor_deltas.bias
proposal_generator.anchor_generator.cell_anchors.0
proposal_generator.anchor_generator.cell_anchors.1
proposal_generator.anchor_generator.cell_anchors.2
proposal_generator.anchor_generator.cell_anchors.3
proposal_generator.anchor_generator.cell_anchors.4
roi_heads.box_head.fc1.weight
roi_heads.box_head.fc1.bias
roi_heads.box_head.fc2.weight
roi_heads.box_head.fc2.bias
roi_heads.box_predictor.cls_score.weight
roi_heads.box_predictor.cls_score.bias
roi_heads.box_predictor.bbox_pred.weight
roi_heads.box_predictor.bbox_pred.bias
'''
